// Bundled demo data so the frontend renders a complete, realistic view when no
// backend is reachable (e.g. a Vercel preview deploy before the Render API is
// wired up). Mirrors the backend CCF seed in app/seed/ccf_reference.py.
import type {
  AIGovernanceSummary,
  AIGovernanceReview,
  AIGuardrail,
  AIComplianceTask,
  AIImpactAssessment,
  AISystem,
  AIVendor,
  ControlCoverage,
  Framework,
  ISO42001Control,
  MedicalAIRisk,
  Summary,
  TrustCenter,
} from "./api";

export const demoSummary: Summary = {
  frameworks: 3,
  requirements: 16,
  common_controls: 6,
  mappings: 18,
};

export const demoFrameworks: Framework[] = [
  {
    id: "demo-soc2",
    key: "soc2",
    name: "SOC 2",
    version: "2017 TSC",
    authority: "AICPA",
    description:
      "Trust Services Criteria for Security, Availability, Processing Integrity, Confidentiality, and Privacy.",
    category: "enterprise",
    requirement_count: 5,
  },
  {
    id: "demo-pci",
    key: "pci_dss",
    name: "PCI DSS",
    version: "v4.0.1",
    authority: "PCI Security Standards Council",
    description: "Payment Card Industry Data Security Standard.",
    category: "enterprise",
    requirement_count: 5,
  },
  {
    id: "demo-nist",
    key: "nist_800_53",
    name: "NIST 800-53",
    version: "Rev 5",
    authority: "NIST",
    description:
      "Security and Privacy Controls for Information Systems and Organizations.",
    category: "enterprise",
    requirement_count: 6,
  },
];

export const demoCoverage: ControlCoverage[] = [
  {
    id: "demo-crypto-001",
    key: "CCF-CRYPTO-001",
    name: "Data Encryption at Rest",
    domain: "Cryptographic Protections",
    description:
      "All sensitive data and account data is encrypted at rest using approved, strong cryptography with managed keys.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "SC-28", title: "Protection of information at rest", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "3.5", title: "Protect stored account data", relationship_type: "subset" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC6.1", title: "Logical access security controls", relationship_type: "intersects" },
    ],
  },
  {
    id: "demo-net-001",
    key: "CCF-NET-001",
    name: "Network Boundary Protection",
    domain: "Network Security",
    description:
      "Boundary defenses monitor and restrict traffic at external and key internal boundaries.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "SC-7", title: "Boundary protection", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "1.2", title: "Network security controls configuration", relationship_type: "subset" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC6.6", title: "Boundary protection", relationship_type: "intersects" },
    ],
  },
  {
    id: "demo-crypto-002",
    key: "CCF-CRYPTO-002",
    name: "Encryption in Transit",
    domain: "Cryptographic Protections",
    description:
      "Sensitive data is protected with strong cryptography (TLS 1.2+) during transmission over untrusted networks.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "SC-8", title: "Transmission confidentiality and integrity", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "1.2", title: "Network security controls configuration", relationship_type: "intersects" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC6.7", title: "Restrict data transmission", relationship_type: "intersects" },
    ],
  },
  {
    id: "demo-iam-001",
    key: "CCF-IAM-001",
    name: "Identity & Access Management",
    domain: "Identification & Authentication",
    description:
      "User accounts are provisioned, reviewed, and de-provisioned under least privilege, with strong (multi-factor) authentication.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "AC-2", title: "Account management", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "8.3", title: "Strong authentication for access", relationship_type: "subset" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC6.1", title: "Logical access security controls", relationship_type: "intersects" },
    ],
  },
  {
    id: "demo-log-001",
    key: "CCF-LOG-001",
    name: "Audit Logging & Monitoring",
    domain: "Continuous Monitoring",
    description:
      "Security-relevant events are logged centrally and monitored for anomalies and suspicious activity.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "AU-2", title: "Event logging", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "10.2", title: "Audit logs capture events", relationship_type: "subset" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC7.2", title: "Security event monitoring", relationship_type: "intersects" },
    ],
  },
  {
    id: "demo-sdlc-001",
    key: "CCF-SDLC-001",
    name: "Secure Change Management",
    domain: "Change Management",
    description:
      "Changes to systems and software are authorized, tested, and securely developed before deployment.",
    frameworks_covered: ["NIST 800-53", "PCI DSS", "SOC 2"],
    requirements: [
      { framework_key: "nist_800_53", framework_name: "NIST 800-53", citation: "CM-3", title: "Configuration change control", relationship_type: "equal" },
      { framework_key: "pci_dss", framework_name: "PCI DSS", citation: "6.3", title: "Security in software development", relationship_type: "intersects" },
      { framework_key: "soc2", framework_name: "SOC 2", citation: "CC8.1", title: "Change management", relationship_type: "intersects" },
    ],
  },
];

const isoControls: Array<[string, string, string, string]> = [
  ["A.2", "AI policy", "A.2.1", "AI policy"],
  ["A.2", "AI policy", "A.2.2", "Policy alignment"],
  ["A.2", "AI policy", "A.2.3", "AI management objectives"],
  ["A.2", "AI policy", "A.2.4", "Policy communication and review"],
  ["A.3", "Internal organization", "A.3.1", "AI roles and responsibilities"],
  ["A.3", "Internal organization", "A.3.2", "Reporting AI concerns"],
  ["A.3", "Internal organization", "A.3.3", "Segregation of duties"],
  ["A.3", "Internal organization", "A.3.4", "Competence and awareness ownership"],
  ["A.4", "Resources", "A.4.1", "AI resource inventory"],
  ["A.4", "Resources", "A.4.2", "Tooling and environment controls"],
  ["A.4", "Resources", "A.4.3", "Human resources for AI"],
  ["A.4", "Resources", "A.4.4", "External AI resources"],
  ["A.5", "Impact assessment", "A.5.1", "Impact assessment process"],
  ["A.5", "Impact assessment", "A.5.2", "Individual and societal impacts"],
  ["A.5", "Impact assessment", "A.5.3", "Impact assessment documentation"],
  ["A.5", "Impact assessment", "A.5.4", "Impact reassessment triggers"],
  ["A.6", "AI system lifecycle", "A.6.1", "AI system requirements"],
  ["A.6", "AI system lifecycle", "A.6.2", "Design and development controls"],
  ["A.6", "AI system lifecycle", "A.6.3", "Verification and validation"],
  ["A.6", "AI system lifecycle", "A.6.4", "Deployment approval"],
  ["A.6", "AI system lifecycle", "A.6.5", "Operation and monitoring"],
  ["A.6", "AI system lifecycle", "A.6.6", "Change and retirement"],
  ["A.6", "AI system lifecycle", "A.6.7", "Technical documentation"],
  ["A.6", "AI system lifecycle", "A.6.8", "Event logs and traceability"],
  ["A.7", "Data for AI systems", "A.7.1", "Data specification"],
  ["A.7", "Data for AI systems", "A.7.2", "Data acquisition"],
  ["A.7", "Data for AI systems", "A.7.3", "Data quality"],
  ["A.7", "Data for AI systems", "A.7.4", "Data provenance"],
  ["A.7", "Data for AI systems", "A.7.5", "Data preparation and protection"],
  ["A.8", "Transparency", "A.8.1", "Information for users"],
  ["A.8", "Transparency", "A.8.2", "Transparency notices"],
  ["A.8", "Transparency", "A.8.3", "External reporting and incidents"],
  ["A.9", "Use of AI systems", "A.9.1", "Responsible use process"],
  ["A.9", "Use of AI systems", "A.9.2", "Intended use controls"],
  ["A.9", "Use of AI systems", "A.9.3", "Human oversight and instructions"],
  ["A.10", "Third-party and customer relationships", "A.10.1", "Responsibility allocation"],
  ["A.10", "Third-party and customer relationships", "A.10.2", "Supplier controls and SBOM"],
  ["A.10", "Third-party and customer relationships", "A.10.3", "Customer relationship controls"],
];

export const demoAIGovernanceSummary: AIGovernanceSummary = {
  ai_systems: 3,
  iso42001_controls: 38,
  high_risk_systems: 1,
  gpai_systems: 1,
  open_tasks: 8,
  passing_guardrails: 6,
  trust_center_frameworks: 5,
  evidence_items: 12,
  missing_evidence: 5,
  overdue_reviews: 1,
};

export const demoISO42001Controls: ISO42001Control[] = isoControls.map(
  ([objective_code, objective_title, control_id, title]) => ({
    id: `demo-${control_id}`,
    objective_code,
    objective_title,
    control_id,
    title,
    description: `${title} control mapped into the AI management system.`,
    implementation_guidance: `Assign an owner, evidence source, and review cadence for ${control_id}.`,
    audit_evidence: "Policy, procedure, review record, technical evidence, or system attestation.",
  }),
);

export const demoAISystems: AISystem[] = [
  {
    id: "demo-ai-1",
    name: "Vendor Risk Copilot",
    owner: "GRC Automation",
    business_purpose: "Assists analysts with third-party risk questionnaire review and evidence summarization.",
    source_type: "internal",
    provider_name: "Combuyn",
    model_type: "retrieval augmented LLM workflow",
    foundation_model_used: "private hosted foundation model",
    deployment_environment: "private VPC",
    lifecycle_stage: "testing",
    regulatory_role: "Provider",
    eu_market: true,
    medical_device_related: false,
    customer_data_training_policy: "blocked by contract and architecture",
    prompt_completion_training_policy: "blocked by contract and architecture",
    data_classes: { inputs: ["vendor questionnaires", "customer prompts"] },
    latest_classification: {
      id: "demo-classification-1",
      actor_role: "Provider",
      risk_tier: "Limited Risk Systems",
      regulatory_scope: "transparency_obligations",
      questionnaire_version: "eu-ai-act-15q-v1",
      questionnaire_answers: { direct_user_interaction: true },
      rationale: "Direct user interaction triggers transparency obligations.",
    },
  },
  {
    id: "demo-ai-2",
    name: "Medical Triage Risk Scorer",
    owner: "Medical Device Engineering",
    business_purpose: "Scores patient triage risk for clinical review as part of a regulated medical workflow.",
    source_type: "third_party",
    provider_name: "ClinicalAI Vendor",
    model_type: "classification model",
    foundation_model_used: "none",
    deployment_environment: "private VPC",
    lifecycle_stage: "development",
    regulatory_role: "Deployer",
    eu_market: true,
    medical_device_related: true,
    customer_data_training_policy: "blocked",
    prompt_completion_training_policy: "not applicable",
    data_classes: { restricted: ["PHI", "regulated medical data"] },
    latest_classification: {
      id: "demo-classification-2",
      actor_role: "Deployer",
      risk_tier: "High-Risk Systems",
      regulatory_scope: "high_risk_ai_system",
      questionnaire_version: "eu-ai-act-15q-v1",
      questionnaire_answers: { medical_or_critical_infrastructure: true },
      rationale: "Medical and safety-component use requires high-risk workflow controls.",
    },
  },
  {
    id: "demo-ai-3",
    name: "Foundation Model Gateway",
    owner: "Platform Security",
    business_purpose: "Central gateway enforcing private LLM routing, logging, and prompt safety policy.",
    source_type: "third_party",
    provider_name: "Hosted Model Provider",
    model_type: "foundation model gateway",
    foundation_model_used: "general purpose foundation model",
    deployment_environment: "private endpoint",
    lifecycle_stage: "deployed",
    regulatory_role: "Deployer",
    eu_market: true,
    medical_device_related: false,
    customer_data_training_policy: "blocked by zero-retention agreement",
    prompt_completion_training_policy: "blocked by zero-retention agreement",
    data_classes: { inputs: ["prompts", "retrieved context"] },
    latest_classification: {
      id: "demo-classification-3",
      actor_role: "Deployer",
      risk_tier: "General Purpose AI (GPAI) Models",
      regulatory_scope: "gpai_model",
      questionnaire_version: "eu-ai-act-15q-v1",
      questionnaire_answers: { general_purpose_model: true },
      rationale: "The system routes a general-purpose foundation model.",
    },
  },
];

export const demoTasks: AIComplianceTask[] = [
  {
    id: "demo-task-1",
    ai_system_id: "demo-ai-2",
    system_name: "Medical Triage Risk Scorer",
    framework: "EU AI Act",
    obligation: "Use the system according to provider instructions and maintain human oversight.",
    owner_role: "Deployer",
    status: "open",
    due_offset_days: 30,
    evidence_required: ["use procedure", "oversight record"],
  },
  {
    id: "demo-task-2",
    ai_system_id: "demo-ai-3",
    system_name: "Foundation Model Gateway",
    framework: "EU AI Act",
    obligation: "Collect provider GPAI documentation and verify downstream-use boundaries.",
    owner_role: "Deployer",
    status: "open",
    due_offset_days: 30,
    evidence_required: ["vendor documentation", "use-case review"],
  },
  {
    id: "demo-task-3",
    ai_system_id: "demo-ai-1",
    system_name: "Vendor Risk Copilot",
    framework: "EU AI Act",
    obligation: "Publish transparency notice for direct AI interaction.",
    owner_role: "Provider",
    status: "open",
    due_offset_days: 30,
    evidence_required: ["user notice", "content labeling"],
  },
];

export const demoGuardrails: AIGuardrail[] = demoAISystems.map((system) => ({
  ai_system_id: system.id,
  system_name: system.name,
  privacy_status: "passing",
  customer_data_training_blocked: true,
  prompt_completion_training_blocked: true,
  retention_policy: "Zero retention unless enterprise retention is explicitly configured.",
  infrastructure_status: "passing",
  model_isolation_confirmed: true,
  encryption_at_rest: true,
  encryption_in_transit: true,
  private_network_path: true,
  network_path_type: "VPC PrivateLink",
}));

export const demoImpactAssessments: AIImpactAssessment[] = demoAISystems.map((system) => ({
  id: `impact-${system.id}`,
  ai_system_id: system.id,
  system_name: system.name,
  lifecycle_stage: system.lifecycle_stage,
  mandatory_review_status:
    system.lifecycle_stage === "deployed" ? "completed" : "required before production",
  nist_govern: { owner: system.owner, policy: "AI policy and EU AI Act role recorded" },
  nist_map: { context: system.business_purpose, affected_parties: ["customers", "operators"] },
  nist_measure: { metrics: ["accuracy", "drift", "privacy boundary", "human override"] },
  nist_manage: { controls: ["human review", "logging", "incident escalation"] },
  data_provenance: "Sources, licenses, lineage, and transformations must be documented before approval.",
  data_quality: "Quality review covers representativeness, bias, completeness, and fitness for intended use.",
  training_data_protections: "Training data is encrypted, access-controlled, minimized, and excluded from provider training.",
  residual_risk: system.medical_device_related ? "high" : "medium",
  approval_status: "pending review",
}));

export const demoAIReviews: AIGovernanceReview[] = [
  {
    id: "review-demo-1",
    ai_system_id: "demo-ai-3",
    system_name: "Foundation Model Gateway",
    review_name: "Foundation Model Gateway deployment readiness",
    review_type: "deployment readiness",
    status: "approved with conditions",
    risk_level: "medium",
    reviewer: "AI Governance Council",
    decision_summary:
      "Approved for private endpoint use with quarterly evidence refresh and provider documentation review.",
    next_review_date: "2026-06-07",
    evidence_ready: 4,
    evidence_missing: 0,
    evidence_items: [
      {
        id: "review-demo-1-evidence-1",
        requirement: "Risk assessment",
        evidence_type: "assessment",
        title: "Foundation Model Gateway impact and risk assessment",
        evidence_uri: "trust://ai-evidence/foundation-model-gateway/risk-assessment",
        owner: "Platform Security",
        status: "accepted",
        notes: "Control owner reviewed residual risk and mitigation plan.",
      },
      {
        id: "review-demo-1-evidence-2",
        requirement: "Data governance",
        evidence_type: "attestation",
        title: "Foundation Model Gateway data provenance and training exclusion",
        evidence_uri: "trust://ai-evidence/foundation-model-gateway/data-governance",
        owner: "Platform Security",
        status: "provided",
        notes: "Data source, retention, and training boundary evidence.",
      },
      {
        id: "review-demo-1-evidence-3",
        requirement: "Human oversight",
        evidence_type: "procedure",
        title: "Foundation Model Gateway human oversight procedure",
        evidence_uri: "trust://ai-evidence/foundation-model-gateway/human-oversight",
        owner: "Platform Security",
        status: "provided",
        notes: "Reviewer roles, override path, and escalation workflow.",
      },
      {
        id: "review-demo-1-evidence-4",
        requirement: "Transparency notice",
        evidence_type: "notice",
        title: "Foundation Model Gateway user and customer notice",
        evidence_uri: "trust://ai-evidence/foundation-model-gateway/transparency-notice",
        owner: "Platform Security",
        status: "accepted",
        notes: "EU AI Act notice and customer-facing disclosure package.",
      },
    ],
  },
  {
    id: "review-demo-2",
    ai_system_id: "demo-ai-2",
    system_name: "Medical Triage Risk Scorer",
    review_name: "Medical Triage Risk Scorer deployment readiness",
    review_type: "deployment readiness",
    status: "under review",
    risk_level: "high",
    reviewer: "AI Governance Council",
    decision_summary:
      "Clinical validation, SOUP supplier evidence, and human oversight records are required before production approval.",
    next_review_date: "2026-07-01",
    evidence_ready: 1,
    evidence_missing: 3,
    evidence_items: [
      {
        id: "review-demo-2-evidence-1",
        requirement: "Risk assessment",
        evidence_type: "assessment",
        title: "Medical Triage Risk Scorer impact and risk assessment",
        evidence_uri: "trust://ai-evidence/medical-triage-risk-scorer/risk-assessment",
        owner: "Medical Device Engineering",
        status: "accepted",
        notes: "Control owner reviewed residual risk and mitigation plan.",
      },
      {
        id: "review-demo-2-evidence-2",
        requirement: "Data governance",
        evidence_type: "attestation",
        title: "Medical Triage Risk Scorer data provenance and training exclusion",
        evidence_uri: "",
        owner: "Medical Device Engineering",
        status: "missing",
        notes: "Data source, retention, and training boundary evidence.",
      },
      {
        id: "review-demo-2-evidence-3",
        requirement: "Human oversight",
        evidence_type: "procedure",
        title: "Medical Triage Risk Scorer human oversight procedure",
        evidence_uri: "",
        owner: "Medical Device Engineering",
        status: "missing",
        notes: "Reviewer roles, override path, and escalation workflow.",
      },
      {
        id: "review-demo-2-evidence-4",
        requirement: "Transparency notice",
        evidence_type: "notice",
        title: "Medical Triage Risk Scorer user and customer notice",
        evidence_uri: "",
        owner: "Medical Device Engineering",
        status: "missing",
        notes: "EU AI Act notice and customer-facing disclosure package.",
      },
    ],
  },
  {
    id: "review-demo-3",
    ai_system_id: "demo-ai-1",
    system_name: "Vendor Risk Copilot",
    review_name: "Vendor Risk Copilot deployment readiness",
    review_type: "deployment readiness",
    status: "pending evidence",
    risk_level: "medium",
    reviewer: "AI Governance Council",
    decision_summary:
      "Transparency notice and evaluation record must be accepted before general availability.",
    next_review_date: "2026-07-17",
    evidence_ready: 2,
    evidence_missing: 2,
    evidence_items: [
      {
        id: "review-demo-3-evidence-1",
        requirement: "Risk assessment",
        evidence_type: "assessment",
        title: "Vendor Risk Copilot impact and risk assessment",
        evidence_uri: "trust://ai-evidence/vendor-risk-copilot/risk-assessment",
        owner: "GRC Automation",
        status: "accepted",
        notes: "Control owner reviewed residual risk and mitigation plan.",
      },
      {
        id: "review-demo-3-evidence-2",
        requirement: "Data governance",
        evidence_type: "attestation",
        title: "Vendor Risk Copilot data provenance and training exclusion",
        evidence_uri: "trust://ai-evidence/vendor-risk-copilot/data-governance",
        owner: "GRC Automation",
        status: "provided",
        notes: "Data source, retention, and training boundary evidence.",
      },
      {
        id: "review-demo-3-evidence-3",
        requirement: "Human oversight",
        evidence_type: "procedure",
        title: "Vendor Risk Copilot human oversight procedure",
        evidence_uri: "",
        owner: "GRC Automation",
        status: "missing",
        notes: "Reviewer roles, override path, and escalation workflow.",
      },
      {
        id: "review-demo-3-evidence-4",
        requirement: "Transparency notice",
        evidence_type: "notice",
        title: "Vendor Risk Copilot user and customer notice",
        evidence_uri: "",
        owner: "GRC Automation",
        status: "missing",
        notes: "EU AI Act notice and customer-facing disclosure package.",
      },
    ],
  },
];

export const demoMedicalRisks: MedicalAIRisk[] = [
  {
    id: "medical-risk-demo",
    ai_system_id: "demo-ai-2",
    system_name: "Medical Triage Risk Scorer",
    soup_component: "ClinicalAI Vendor Scoring Engine",
    training_validation_test_split_risk:
      "Document split strategy, leakage prevention, stratification, clinical representativeness, and locked test-set governance.",
    explainable_ai_evaluation:
      "Assess whether outputs are causally meaningful or correlational, and how clinicians should interpret uncertainty.",
    performative_prediction_risk:
      "Address whether prediction changes clinical behavior and creates feedback loops that alter outcomes.",
    clinical_validation_status: "protocol required",
    risk_controls: "Clinician override, locked validation protocol, post-market monitoring, and SOUP supplier review.",
    review_status: "required",
  },
];

export const demoVendors: AIVendor[] = [
  {
    id: "vendor-1",
    name: "Hosted Model Provider",
    service: "Foundation model API",
    onboarding_status: "approved with guardrails",
    sbom_received: true,
    sbom_format: "CycloneDX",
    supply_chain_risk: "medium",
    data_processing_role: "subprocessor",
    evidence_uri: "trust://vendors/hosted-model-provider/sbom",
  },
  {
    id: "vendor-2",
    name: "ClinicalAI Vendor",
    service: "Medical triage scoring model",
    onboarding_status: "risk review required",
    sbom_received: false,
    sbom_format: "",
    supply_chain_risk: "high",
    data_processing_role: "processor",
    evidence_uri: "trust://vendors/clinical-ai-vendor",
  },
];

export const demoTrustCenter: TrustCenter = {
  frameworks: [
    {
      id: "trust-soc2",
      framework: "SOC 2",
      status: "monitored",
      coverage_percent: 86,
      monitored_controls: 42,
      public_summary: "SOC 2 control evidence is continuously monitored with gated report access.",
    },
    {
      id: "trust-iso27001",
      framework: "ISO 27001",
      status: "in progress",
      coverage_percent: 73,
      monitored_controls: 51,
      public_summary: "ISO 27001 control ownership and evidence collection are actively tracked.",
    },
    {
      id: "trust-hipaa",
      framework: "HIPAA",
      status: "monitored",
      coverage_percent: 79,
      monitored_controls: 28,
      public_summary: "HIPAA safeguards are tracked for healthcare workflows.",
    },
    {
      id: "trust-ai-act",
      framework: "EU AI Act",
      status: "mapped",
      coverage_percent: 68,
      monitored_controls: 31,
      public_summary: "AI systems are inventoried and classified against transparency obligations.",
    },
    {
      id: "trust-iso42001",
      framework: "ISO/IEC 42001",
      status: "mapped",
      coverage_percent: 61,
      monitored_controls: 38,
      public_summary: "AIMS Annex A controls are seeded and mapped to AI systems.",
    },
  ],
  ai_transparency: demoAISystems.map((system) => ({
    id: `trust-${system.id}`,
    system_name: system.name,
    direct_user_interaction: system.name === "Vendor Risk Copilot",
    biometric_data: false,
    synthetic_content: false,
    deepfake_generation: false,
    eu_transparency_notice:
      system.name === "Vendor Risk Copilot" ? "required" : "not_required",
    public_summary: system.business_purpose,
  })),
  documents: [
    {
      id: "doc-soc2",
      document_name: "SOC 2 Type 2 Report",
      sensitivity: "confidential",
      nda_required: true,
      nda_status: "required",
      request_workflow: "Business justification, automated NDA, approval, watermarking.",
      fulfillment_status: "gated",
    },
    {
      id: "doc-pentest",
      document_name: "Penetration Test Executive Summary",
      sensitivity: "confidential",
      nda_required: true,
      nda_status: "required",
      request_workflow: "Business justification, automated NDA, approval, watermarking.",
      fulfillment_status: "gated",
    },
    {
      id: "doc-ai",
      document_name: "AI System Transparency Package",
      sensitivity: "restricted",
      nda_required: true,
      nda_status: "required",
      request_workflow: "Business justification, automated NDA, approval, watermarking.",
      fulfillment_status: "gated",
    },
  ],
};
